### ISSUE TITLE
licenseAreaExtent field is using depecrated value in newly released study guide configs version ITS_Study_Guide_V3_07_15_2021

### ISSUE THREAD

**Issue by diptivete** [NTIA/sas-study-guide#2]
We are seeing some issues while running latest study guide configs for Tranche 1 from - 
[https://github.com/NTIA/sas-study-guide/tree/SASCBRS-210_Updated_ExpirationTime_FIPS/Published%20Study%20Guides/ITS_Study_Guide_V3_07_15_2021](url)

licenseAreaExtent field in below configs is pointing to deprecated value of “zone/census_tract/census/2010/<county_fips_code>”.
This field should now point to “zone/county/census/2017/<county_fips_code>”.

Similar fix was made in Test Harness code recently on top of v1.0.27
Reference to test harness issue + fix:
 ##https://github.com/Wireless-Innovation-Forum/Spectrum-Access-System/issues/901

List of T1 configs with deprecated value in licenseAreaExtent field -
test_WINNF_FT_S_FAD_1/FAD-01_T1_C00_A_Waldoboro-ME_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_FAD_1/FAD-01_T1_C00_A_Waldoboro-ME_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20063",
test_WINNF_FT_S_FAD_1/FAD-01_T1_C00_B_Silverthorne-CO_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_FAD_1/FAD-01_T1_C00_B_Silverthorne-CO_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20063",
test_WINNF_FT_S_FAD_1/FAD-01_T1_C00_M_Bremerton-WA_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_FAD_1/FAD-01_T1_C00_M_Bremerton-WA_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20063",
test_WINNF_FT_S_FAD_1/FAD-01_T1_C00_M_El-Paso-TX_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_FAD_1/FAD-01_T1_C00_M_El-Paso-TX_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20063",
test_WINNF_FT_S_FAD_1/FAD-01_T1_C00_M_Myrtle-Beach-SC_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_FAD_1/FAD-01_T1_C00_M_Myrtle-Beach-SC_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20063",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C00_A_Waldoboro-ME_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C00_B_Silverthorne-CO_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C00_M_Bremerton-WA_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C00_M_El-Paso-TX_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C00_M_Myrtle-Beach-SC_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C00_M_Table-Mountain-03-CO_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C01_A_Waldoboro-ME_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C01_B_Silverthorne-CO_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C01_M_Bremerton-WA_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C01_M_El-Paso-TX_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C01_M_Myrtle-Beach-SC_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C02_A_Waldoboro-ME_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C02_B_Silverthorne-CO_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C02_M_Bremerton-WA_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C02_M_El-Paso-TX_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C02_M_Myrtle-Beach-SC_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C03_A_Waldoboro-ME_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C03_B_Silverthorne-CO_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C03_M_Bremerton-WA_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C03_M_El-Paso-TX_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C03_M_Myrtle-Beach-SC_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C04_A_Waldoboro-ME_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C04_B_Silverthorne-CO_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C04_M_Bremerton-WA_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C04_M_El-Paso-TX_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C04_M_Myrtle-Beach-SC_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C05_A_Waldoboro-ME_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C05_B_Silverthorne-CO_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C05_M_Bremerton-WA_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C05_M_El-Paso-TX_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C05_M_Myrtle-Beach-SC_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_GRA_17/GRA-17_T1_C75_A_Waldoboro-ME_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/23013",
test_WINNF_FT_S_MCP_1/MCP-01_T1_C00_Nov_14_test_7_M3.config:              "licenseAreaExtent": "zone/census_tract/census/2010/41005",
test_WINNF_FT_S_MCP_1/MCP-01_T1_C00_Nov_14_test_7_M3.config:              "licenseAreaExtent": "zone/census_tract/census/2010/53035",
test_WINNF_FT_S_MCP_1/MCP-01_T1_C00_Nov_14_test_7_M3.config:              "licenseAreaExtent": "zone/census_tract/census/2010/53053",
test_WINNF_FT_S_MCP_1/MCP-01_T1_C04_multiple_protected_entities-sample_rev02_M3.config:              "licenseAreaExtent": "zone/census_tract/census/2010/12031",
test_WINNF_FT_S_PPR_1/PPR-01_T1_C00_M_Bremerton_M3.config:              "licenseAreaExtent": "zone/census_tract/census/2010/53035",
test_WINNF_FT_S_PPR_1/PPR-01_T1_C00_M_ Jacksonville_M3.config:              "licenseAreaExtent": "zone/census_tract/census/2010/12031",
test_WINNF_FT_S_PPR_1/PPR-01_T1_C00_M_Norfolk_M3.config:              "licenseAreaExtent": "zone/census_tract/census/2010/51710",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C00_A_Waldoboro-ME_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C00_A_Waldoboro-ME_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20063",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C00_B_Silverthorne-CO_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C00_B_Silverthorne-CO_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20063",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C00_M_Bremerton-WA_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C00_M_Bremerton-WA_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20063",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C00_M_El-Paso-TX_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C00_M_El-Paso-TX_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20063",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C00_M_Myrtle-Beach-SC_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C00_M_Myrtle-Beach-SC_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20063",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C01_A_Waldoboro-ME_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C01_A_Waldoboro-ME_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20063",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C01_B_Silverthorne-CO_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C01_B_Silverthorne-CO_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20063",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C01_M_Bremerton-WA_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C01_M_Bremerton-WA_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20063",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C01_M_El-Paso-TX_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C01_M_El-Paso-TX_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20063",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C01_M_Myrtle-Beach-SC_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C01_M_Myrtle-Beach-SC_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20063",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C02_A_Waldoboro-ME_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C02_A_Waldoboro-ME_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20063",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C02_B_Silverthorne-CO_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C02_B_Silverthorne-CO_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20063",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C02_M_Bremerton-WA_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C02_M_Bremerton-WA_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20063",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C02_M_El-Paso-TX_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C02_M_El-Paso-TX_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20063",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C02_M_Myrtle-Beach-SC_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C02_M_Myrtle-Beach-SC_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20063",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C03_A_Waldoboro-ME_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C03_A_Waldoboro-ME_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20063",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C03_B_Silverthorne-CO_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C03_B_Silverthorne-CO_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20063",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C03_M_Bremerton-WA_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C03_M_Bremerton-WA_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20063",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C03_M_El-Paso-TX_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C03_M_El-Paso-TX_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20063",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C03_M_Myrtle-Beach-SC_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20041",
test_WINNF_FT_S_SIQ_12/SIQ-12_T1_C03_M_Myrtle-Beach-SC_M3.config:        "licenseAreaExtent": "zone/census_tract/census/2010/20063",

Thanks for your time for checking this.

**Comment by jhazentia** [comment]
Thanks for finding this. We will fix.

**Comment by diptivete** [comment]
Thanks for fixing it quickly. We'll give it a try and let you know.
